project_id = "fbhcciagsdafmszzmudm"

[functions.scrape-cbn]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.check-compliance]
verify_jwt = false

[functions.summarize-document]
verify_jwt = false

[functions.legal-chat]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.scrape-african-law]
verify_jwt = false

[functions.crawl-african-law]
verify_jwt = false

[functions.due-diligence]
verify_jwt = false
